"""Generates a working, commented ``opentrials.project`` YAML file for `opentrials init`.

Deliberately produces something that runs, not just a template: the
generated file is valid against ``config.project.load_project`` as-is
(confirmed directly in ``tests/unit/test_project_scaffold.py``, not
assumed), using the one model this project ships registered by default.
A researcher can `opentrials validate`/`opentrials run` it immediately,
then edit the dose, population, or arms to match their own question.
"""

from __future__ import annotations

PROJECT_SCAFFOLD_TEMPLATE = '''\
# OpenTrials project configuration.
#
# Generated by `opentrials init`. This file already runs as-is (try
# `opentrials validate {filename}` then `opentrials run {filename}`) --
# edit the population, arms, or dose below to match your own question.
#
# See docs/quickstart.md for a walkthrough, and
# examples/aciclovir_dose_comparison.yaml for a two-arm comparison example.

schema: opentrials.project
schema_version: 1.0.0
payload:
  # Which registered model this project executes through. Omit this key
  # entirely if exactly one model is registered (see `opentrials models
  # list`) -- the SDK resolves it automatically and this comment is here
  # so you know where to look if you ever need to be explicit.
  model_id: {model_id}

  trial:
    trial_id: {trial_id}
    title: {title}
    question_of_interest: What plasma concentration does this dose produce?

    # The virtual population this trial's intervention will be executed
    # against. A fresh population is generated (and immutably persisted)
    # the first time this project runs.
    population:
      id: {population_id}
      size: 10
      seed: 1
      generator_version: "0.1.0"
      age_range:
        minimum: {{value: 18, unit: year, value_type: ASSUMED}}
        maximum: {{value: 65, unit: year, value_type: ASSUMED}}
      sexes: [FEMALE]

    # One arm, one verified dose -- the whole population receives it.
    # Add a second arm (see examples/aciclovir_dose_comparison.yaml) and
    # set randomization to PARALLEL to run a real multi-arm comparison
    # instead.
    arms:
      - arm_id: standard
        name: standard
        allocation: 1.0
        intervention:
          intervention_id: standard-intervention
          compound:
            identity: {{compound_id: aciclovir, preferred_name: Aciclovir}}
          regimen:
            regimen_id: standard-regimen
            doses:
              - amount: {{value: 250, unit: mg, value_type: ASSUMED}}
                route: INTRAVENOUS
                administration_time: {{value: 0, unit: min, value_type: ASSUMED}}
                infusion_duration: {{value: 10, unit: min, value_type: ASSUMED}}
    randomization: NONE

    endpoints:
      - endpoint_id: plasma-concentration
        endpoint_type: PK
        measurement: plasma aciclovir concentration
        time_window:
          start: {{value: 0, unit: h, value_type: ASSUMED}}
          end: {{value: 24, unit: h, value_type: ASSUMED}}
        aggregation: RAW
        missingness_rule: REPORT
        analysis_method: PK endpoints
        unit: umol/L
    seed: 1
'''


def generate_project_scaffold(
    *,
    filename: str = "project.yaml",
    trial_id: str = "MY-FIRST-TRIAL",
    title: str = "My first virtual trial",
    population_id: str = "my-first-population",
    model_id: str = "osp.aciclovir.vergin-1995-iv",
) -> str:
    """Render a working, commented project YAML -- see module docstring."""
    return PROJECT_SCAFFOLD_TEMPLATE.format(
        filename=filename,
        trial_id=trial_id,
        title=title,
        population_id=population_id,
        model_id=model_id,
    )
